### ISSUE TITLE
internal-binary

### ISSUE THREAD

**Issue by vinay92** [SoftwareEngineeringToolDemos/FSE-2013-aPET#4]
There is no link to the internal binaries in the README.

**Comment by vinay92** [comment]
Hey Manish, could you undo your changes so that I can fix the issue. Thanks

**Comment by manish211** [comment]
@vinay92 Yes. I have reset the repository to previous version. You can go ahead with the fixes. Thanks.

**Comment by vinay92** [comment]
Fixed the issue via pull request [#1](https://github.com/vinay92/FSE-2013-aPET/pull/1)
