### ISSUE TITLE
links-function

### ISSUE THREAD

**Issue by vinay92** [SoftwareEngineeringToolDemos/FSE-2013-aPET#6]
The "Slightly modified version of the tool" link in the README does not work.

**Comment by manish211** [comment]
This is not required. No modified version of tool in the repository.

**Comment by manish211** [comment]
closed this in the pull request.

**Comment by vinay92** [comment]
Closed in pulled request [#3](https://github.com/SoftwareEngineeringToolDemos/FSE-2013-aPET/pull/8)
